application: rjseducation
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers: 
    
- url: /public/bootstrap/css
  static_dir: css
    
- url: /public/favicon\.ico
  static_files: /public/favicon.ico
  upload: /public/favicon\.ico
  
- url: /mathassignment\.php
  script: public/mathassignment.php
  
- url: .*
  script: /public/index.php
  

