application: rjseducation
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers: 
    
- url: /bootstrap/css
  static_dir: css
  
- url: /font-awesome-4.5.0/css
  static_dir: css
  
- url: /Assets/images
  static_dir: images
    
- url: /public/favicon\.ico
  static_files: /public/favicon.ico
  upload: /public/favicon\.ico
  
- url: /mathassignment\.php
  script: public/mathassignment.php
  
- url: /dutchassignment\.php
  script: public/dutchassignment.php
  
- url: /countingassignment\.php
  script: public/countingassignment.php
  
- url: /membernew\.php
  script: public/membernew.php
 
- url: /layout\.php
  script: layout.php
  
- url: .*
  script: /public/index.php
  

