-- MySQL Script generated by MySQL Workbench
-- 03/24/16 12:57:41
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rjseducation
-- -----------------------------------------------------

USE `rjseducation` ;

-- -----------------------------------------------------
-- Table `rjseducation`.`members`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rjseducation`.`members` ;

CREATE TABLE IF NOT EXISTS `rjseducation`.`members` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `rjseducation`.`members`
-- -----------------------------------------------------
START TRANSACTION;
USE `rjseducation`;
INSERT INTO `rjseducation`.`members` (`id`, `username`, `password`) VALUES (1, 'jmorit', '0e0706cfbb759f8347ae615fedb66a4f');

COMMIT;



